from tkinter import Tk, END
from tkinter.ttk import *
win = Tk()
win.title("Calculator")
win.resizable(0, 0)
output = Entry(win, width=34)
output.grid(column=0, row=0, columnspan=7)
Button(win, text=1, width=7, command=lambda: output.insert(END, 1)).grid(column=0, row=1)
Button(win, text=2, width=7, command=lambda: output.insert(END, 2)).grid(column=1, row=1)
Button(win, text=3, width=7, command=lambda: output.insert(END, 3)).grid(column=0, row=2)
Button(win, text=4, width=7, command=lambda: output.insert(END, 4)).grid(column=1, row=2)
Button(win, text=5, width=7, command=lambda: output.insert(END, 5)).grid(column=0, row=3)
Button(win, text=6, width=7, command=lambda: output.insert(END, 6)).grid(column=1, row=3)
Button(win, text=7, width=7, command=lambda: output.insert(END, 7)).grid(column=0, row=4)
Button(win, text=8, width=7, command=lambda: output.insert(END, 8)).grid(column=1, row=4)
Button(win, text=9, width=7, command=lambda: output.insert(END, 9)).grid(column=0, row=5)
Button(win, text=0, width=7, command=lambda: output.insert(END, 0)).grid(column=1, row=5)
Button(win, text="+", width=7, command=lambda: output.insert(END, "+")).grid(column=2, row=1)
Button(win, text="-", width=7, command=lambda: output.insert(END, "-")).grid(column=3, row=1, columnspan=7)
Button(win, text="*", width=7, command=lambda: output.insert(END, "*")).grid(column=2, row=2)
Button(win, text="/", width=7, command=lambda: output.insert(END, "/")).grid(column=3, row=2, columnspan=7)
Button(win, text="**", width=7, command=lambda: output.insert(END, "**")).grid(column=2, row=3)
Button(win, text="**(1/2)", width=7, command=lambda: output.insert(END, "**(1/2)")).grid(column=3, row=3, columnspan=7)
Button(win, text="(", width=7, command=lambda: output.insert(END, "(")).grid(column=2, row=4)
Button(win, text=")", width=7, command=lambda: output.insert(END, ")")).grid(column=3, row=4, columnspan=7)
Button(win, text=".", width=7, command=lambda: output.insert(END, ".")).grid(column=2, row=5)
Button(win, text="D", width=2, command=lambda: output.delete(len(output.get()) - 1, END)).grid(column=3, row=5)
Button(win, text="=", width=1, command=lambda: parse(output.get())).grid(column=5, row=5)
Button(win, text="C", width=1, command=lambda: output.delete(0, END)).grid(column=4, row=5)
def parse(command):
    output.delete(0, END)
    try:
        output.insert(END, eval(command))
    except:
        output.insert(END, "Error")
win.mainloop()